version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - my_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent storage
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      retries: 5
      timeout: 3s

  fastapi:
    build: .
    container_name: fastapi-app
    volumes:
      - .:/app  # Mounts your local project into the container at /app
    environment:
      - PYTHONPATH=/app/Backend # Ensures Python can import modules from /app/Backend
    ports:
      - "8000:8000"
    networks:
      - my_network
    depends_on:
      postgres:
        condition: service_healthy
    command: uvicorn Backend.app:app --host 0.0.0.0 --port 8000 --reload

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:  # Define named volume
